name: Launcher Build
on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Étape 1 : Checkout du dépôt
      - name: Checkout
        uses: actions/checkout@v2

      # Étape 2 : Obtenir la version
      - name: Get Version
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_ENV

      # Étape 3 : Créer et pousser une balise
      - name: Create and Push Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag ${{ env.version }}
          git push origin ${{ env.version }}

      # Étape 4 : Créer la release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.version }}
          release_name: "Release ${{ env.version }}"
          draft: false
          prerelease: false

      # Étape 5 : Installer Node.js
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Étape 6 : Installer les dépendances
      - name: Install Dependencies
        run: npm ci

      # Étape 7 : Construire l'application
      - name: Build
        run: npm run build

      # Étape 8 : Lister les fichiers générés
      - name: List Dist Directory
        run: ls -R dist

      # Étape 9 : Upload des artefacts dans la release
      - name: Upload Artifacts to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
